server:
  port: 8741
spring:
  application:
    name: server-zipkin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false